<a href="https://colab.research.google.com/github/Pratiksha1699/AI-Mafia-Machine-Learning/blob/main/Pratiksha_More_Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
print(np.show_config())

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10

In [51]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [52]:
a.size

10

#### 5.  How to get the documentation of the numpy add function from the command line?

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [12]:
b = np.zeros(10)
b[4] = 1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [15]:
c = np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [16]:
d = np.arange(10,31)
print("d - Before reverse:",d)
d = d[::-1]
print("d - After reverse:",d)

d - Before reverse: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
d - After reverse: [30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
e = np.linspace(0,8,9)
print(e.reshape(3,3))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [19]:
arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [26]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [28]:
j = np.random.rand(3,3,3)
print(j)

[[[0.48313966 0.49406214 0.14829872]
  [0.18505656 0.25644804 0.13533569]
  [0.75256815 0.95862167 0.69316647]]

 [[0.80693789 0.5516872  0.60653457]
  [0.95662073 0.6082465  0.85498508]
  [0.84221304 0.63732253 0.10320502]]

 [[0.48807893 0.25027509 0.23373383]
  [0.45434618 0.57377719 0.50950968]
  [0.85924042 0.91182035 0.25516658]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [29]:
k = np.random.rand(10,10)
print(k)
print(np.min(k))
print(np.max(k))

[[0.26181126 0.25423185 0.41264828 0.22968152 0.86378172 0.3872117
  0.60015646 0.51737975 0.80737103 0.19036555]
 [0.86877131 0.40803467 0.94193393 0.74195412 0.01304525 0.2144433
  0.53335684 0.97359119 0.23487636 0.28805605]
 [0.70857798 0.63334326 0.60534185 0.20119352 0.03294448 0.35228354
  0.72362473 0.05915221 0.91018701 0.56918202]
 [0.95310626 0.4967905  0.29141375 0.9736546  0.21167516 0.29327171
  0.70585172 0.5173487  0.61651644 0.41862468]
 [0.31794636 0.67184657 0.69292576 0.07546696 0.62818437 0.87610942
  0.22055559 0.0674473  0.48322562 0.55488151]
 [0.64465381 0.23379739 0.8672915  0.54427435 0.683322   0.99104543
  0.41894413 0.17197053 0.02319963 0.5208047 ]
 [0.34717917 0.56581929 0.92705748 0.80576566 0.31309614 0.71069644
  0.78845552 0.96288356 0.10139666 0.82996287]
 [0.1995162  0.00806298 0.38616038 0.41559156 0.34789627 0.94578294
  0.46440019 0.81559008 0.27937358 0.02282743]
 [0.28422242 0.2817272  0.0021786  0.27067041 0.37900136 0.07201277
  0.36490737 0

#### 14. Create a random vector of size 30 and find the mean value

In [30]:
l = np.random.rand(30)
print(l)
print(np.mean(l))

[0.1370747  0.2083581  0.00568342 0.87558556 0.36288732 0.92992356
 0.83608359 0.2081869  0.89263262 0.61469651 0.25416259 0.75911735
 0.47974916 0.83280068 0.32028826 0.39202657 0.47845425 0.98391387
 0.66236004 0.06539029 0.69287479 0.73515899 0.23049725 0.15416888
 0.42280957 0.79919933 0.51835416 0.86173673 0.28855911 0.01942872]
0.5007387623481976


#### 15. Create a 2d array with 1 on the border and 0 inside

In [35]:
m = np.zeros((3,3))
print(m,end="\n\n")
m = np.pad(m,pad_width=1,mode="constant",constant_values=1)
print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [36]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(n,end="\n\n")
n = np.pad(n,pad_width=1,mode="constant",constant_values=0)
print(n)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [38]:
###Outputs are as follows:
##nan
##False
##False
##nan
##True
##False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
o = np.zeros((5,5))
o = np.diag([1,2,3,4],k=-1)
print(o)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [44]:
p = np.zeros((8,8))
p[1::2, ::2] = 1
p[::2, 1::2] = 1
print(p)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [48]:
##q = np.array((6,7,8))
print(np.unravel_index(99,[6,7,8]))

(1, 5, 3)
